# Generated by Django 5.0.7 on 2024-07-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolio_portfoliogallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
