# Generated by Django 5.0.7 on 2024-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
